splitt reservation added
UnionInternationalCheminsdeFer/OSDM pull request #381
Opened 2023-11-16 13:02 UTC by CGantert345

2023-11-16 13:07 UTC, jspetrak requested changes

2023-11-16 13:07 UTC, jspetrak commented on specification/v3.2/OSDM-online-api-v3.2.0_draft.yml
> +        splittSection:
Single 'T'

2023-11-16 14:04 UTC, jspetrak approved these changes

2023-11-20 15:33 UTC, Linus-Turnit commented
When I paste the yaml to swagger editor I get an error
![image](https://github.com/UnionInternationalCheminsdeFer/OSDM/assets/122451962/07ef7c9c-a17c-4350-bb7a-fde654209eb9)

But I can't see what the problem really is.

2023-11-20 15:44 UTC, gadcam commented
> When I paste the yaml to swagger editor I get an error ![image](https://user-images.githubusercontent.com/122451962/284313962-07ef7c9c-a17c-4350-bb7a-fde654209eb9.png)
> 
> But I can't see what the problem really is.

Maybe
```
type: '#/components/schemas/ProductTag'
```
Should be changed into

```
$ref: '#/components/schemas/ProductTag'
```
What do you think ?

2023-11-21 08:12 UTC, Linus-Turnit approved these changes

2023-11-21 08:26 UTC, merged