additional provisionalRefundAmount
UnionInternationalCheminsdeFer/OSDM pull request #512
Opened 2024-04-19 12:20 UTC by CGantert345

2024-04-21 22:23 UTC, jspetrak requested changes

2024-04-21 22:23 UTC, jspetrak commented on specification/v3.3/OSDM-online-api-v3.3.0-draft.yml
> +             price of all unconfiremed preebooked parts in the booking
typo in prebooked

2024-04-21 22:23 UTC, jspetrak commented on specification/v3.3/OSDM-online-api-v3.3.0-draft.yml
> +             price of all unconfiremed preebooked parts in the booking
copy past typo in prebooked

2024-04-22 07:28 UTC, CGantert345 commented on specification/v3.3/OSDM-online-api-v3.3.0-draft.yml
> +             price of all unconfiremed preebooked parts in the booking
typos fixed

2024-04-22 08:06 UTC, jspetrak approved these changes

2024-04-22 08:06 UTC, merged