#469
UnionInternationalCheminsdeFer/OSDM pull request #532
Opened 2024-05-02 14:07 UTC by rolandkla

PATCH for issue "On-hold missing delete operation to cancel the on-hold request #469":
- added DELETE onHoldOffer
- added onHoldOffer to booking response
- removed onHoldOfferId from PATCH
- removed id from onHoldOffer object

2024-05-02 21:21 UTC, jspetrak requested changes
I believe that these two changes are breaking:

> removed onHoldOfferId from PATCH
> removed id from onHoldOffer object

We should probably deprecate them with proper explanation that onHoldOffer.id is ignored as well as onHoldOfferId in the request, and introduce correct PATCH endpoint without ID.

Also note down to remove these in OSDM 4.

2024-05-06 15:33 UTC, rolandkla commented
Re-added:
- the onHoldOfferId in the path of the PATCH and added to DELETE for consistency
- id in OnHoldOffer object

2024-05-10 07:45 UTC, ralfbayer-db approved these changes

2024-05-10 07:46 UTC, jspetrak approved these changes

2024-05-10 07:46 UTC, merged