initial start of v4.0
UnionInternationalCheminsdeFer/OSDM pull request #618
Opened 2024-07-22 07:38 UTC by CGantert345

2024-07-22 08:27 UTC, schlpbch requested changes
I'd propose to switch to Github branches for the different versions of OSDM as it makes back porting features to older versions **much** easier --> topic for next Friday

2024-07-22 09:47 UTC, jspetrak commented
Andreas, I find it easier to have the change done in single commit including backports. If we have version branches, you have to make pull request to each version track separately. Let's discuss that on Friday.

2024-07-22 09:47 UTC, jspetrak approved these changes

2024-07-26 07:52 UTC, schlpbch requested changes
Please double check with your generators whether they can deal with OpenAPI 3.1.0.

2024-08-02 09:08 UTC, jspetrak approved these changes

2024-08-02 09:09 UTC, jspetrak approved these changes

2024-08-02 09:10 UTC, closed without merging