#624 remove maxLenght from #/components/schemas/Link.href
UnionInternationalCheminsdeFer/OSDM pull request #625
Opened 2024-07-25 10:46 UTC by stepanhampl

This change is needed in order to correctly run POST /complaints. Otherwise it fails with this message:

jakarta.validation.UnexpectedTypeException: HV000030: No validator could be found for constraint 'jakarta.validation.constraints.Pattern' validating type 'java.net.URI'. Check configuration for 'decision.delayedJourney[0].links[0].href'

2024-07-25 10:50 UTC, jspetrak requested changes

2024-07-25 10:50 UTC, jspetrak commented on specification/v3.3/OSDM-online-api-v3.3.1.yml
> +  version: 3.3.0
hi @stepanhampl please also adjust version here.

2024-07-25 10:57 UTC, jspetrak approved these changes

2024-07-26 08:21 UTC, closed without merging

2024-07-26 08:21 UTC, schlpbch commented
Please merge to 3.0.0.