#664 TripSearchCriteria - only one of departure/arrival time may be p…
UnionInternationalCheminsdeFer/OSDM pull request #666
Opened 2024-08-22 23:07 UTC by jspetrak

…rovided

2024-08-23 11:37 UTC, VelvetteRld requested changes
Suggesting adjusting the added sentence to not repeat "departure time" twice

2024-08-23 11:37 UTC, VelvetteRld commented on specification/v3.4/OSDM-online-api-v3.4.0-draft.yml
> +            Needs to in local date time format. If departure time is provided the departure time must be omitted.
Should be
"If departure time is provided the arrival time must be omitted." to mimic line 14152

2024-08-23 11:37 UTC, VelvetteRld commented on specification/v4.0/OSDM-online-api-v4.0.0-draft.yml
> +            Needs to in local date time format. If departure time is provided the departure time must be omitted.
Should be
"If departure time is provided the arrival time must be omitted." to mimic line 14006

2024-08-30 21:38 UTC, jspetrak commented
Descriptions fixed based on discussion from the Technical Group Call.

2024-09-20 07:21 UTC, CGantert345 approved these changes

2024-09-20 07:21 UTC, merged