Require tolerant reader pattern
UnionInternationalCheminsdeFer/OSDM pull request #694
Opened 2024-09-20 10:49 UTC by CGantert345

2024-09-24 12:00 UTC, jspetrak commented
@CGantert345 Thanks. I fixed few of my typos in the original text. @ralfbayer-db @nixxus1030 please review when possible.

2024-09-24 14:21 UTC, ralfbayer-db requested changes
Generally approved, nicely written. However, especially in the "Backporting" section, I would replace "vendors" with "implementers", as not all organistions implementing OSDM are actually selling a software product.

2024-09-25 06:54 UTC, jspetrak commented
@ralfbayer-db Agreed and updated. Thanks.

2024-09-25 09:42 UTC, ralfbayer-db approved these changes

2024-09-25 09:51 UTC, merged