More edits to spec documents
UnionInternationalCheminsdeFer/OSDM pull request #813
Opened 2024-12-23 13:55 UTC by xthiba

Found during studying the spec. Perhaps best reviewed commit-by-commit.

2025-01-17 07:59 UTC, jspetrak requested changes

2025-01-17 07:59 UTC, jspetrak commented on spec/catalog-of-code-lists.md
> +| currencies                | `urn:iso`             | `std:iso:4217` | ISO Currency Codes  https://en.wikipedia.org/wiki/ISO_4217
I would prefer to link ISO directly. https://www.iso.org/iso-4217-currency-codes.html

2025-01-17 07:59 UTC, jspetrak commented on spec/catalog-of-code-lists.md
> +| countries                 | `urn:iso`             | `std:iso:3166` | ISO Country Codes  https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
Please link ISO directly. https://www.iso.org/iso-3166-country-codes.html

There is also online browser of the codes. https://www.iso.org/obp/ui/#search/code/

2025-01-17 07:59 UTC, jspetrak commented on spec/synchronization.md
> -- `PASSENGER_CHANGED`
Why is this section removed? `PASSENGER_CHANGED` is still present in OSDM 4.0 Webhooks,

2025-01-17 07:59 UTC, jspetrak commented on spec/technical-principles.md
> -## Error Handling
This is removed because there is separate "Errors and Problems" page? Some of details from this section are not present on that page.

2025-01-17 09:28 UTC, xthiba commented on spec/synchronization.md
> -- `PASSENGER_CHANGED`
this section is duplicated in the file - hard to tell from the context. check here: https://osdm.io/spec/synchronization/

2025-01-17 09:31 UTC, xthiba commented on spec/technical-principles.md
> -## Error Handling
the way i read it, most of the details are described in the RFC and the additional details dont add much value. let me re-add this section so that we can get this PR in...

2025-01-17 11:03 UTC, xthiba commented on spec/catalog-of-code-lists.md
> +| countries                 | `urn:iso`             | `std:iso:3166` | ISO Country Codes  https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
added link to iso

2025-01-17 11:03 UTC, xthiba commented on spec/catalog-of-code-lists.md
> +| currencies                | `urn:iso`             | `std:iso:4217` | ISO Currency Codes  https://en.wikipedia.org/wiki/ISO_4217
added link to iso

2025-01-17 11:04 UTC, xthiba commented on spec/technical-principles.md
> -## Error Handling
i have removed the removal ;-)

2025-01-22 23:50 UTC, jspetrak commented on spec/synchronization.md
> -- `PASSENGER_CHANGED`
I can't find the duplicate with Ctrl + F. Could you advise the line numbers? Above that, there is similar `PURCHASER_CHANGED`.

2025-01-23 08:09 UTC, xthiba commented on spec/synchronization.md
> -- `PASSENGER_CHANGED`
wow - i completely missed that. probably because there is a mistake in there. fixed now - thanks!

2025-01-23 10:07 UTC, jspetrak approved these changes

2025-01-23 10:07 UTC, merged

2025-01-23 10:07 UTC, jspetrak commented on spec/synchronization.md
> -- `PASSENGER_CHANGED`
Yeah, that was missed by both of us, what is actually wrong. Thanks for the review!